### ISSUE TITLE
加油

### ISSUE THREAD

**Issue by hiiiragitukasa** [windshadow233/pvz-toolkit#1]
鼓励一下0star的作者

**Comment by hiiiragitukasa** [comment]
![图片](https://github.com/windshadow233/pvz-toolkit/assets/87431097/c2289ee7-3fb0-4483-b04a-5ac29dd85881)
这是什么情况

**Comment by windshadow233** [comment]
> ![图片](https://user-images.githubusercontent.com/87431097/264465254-c2289ee7-3fb0-4483-b04a-5ac29dd85881.png)
> 这是什么情况

哈哈哈，没注意路径问题。可能需要把src作为工作目录。

**Comment by windshadow233** [comment]
> 鼓励一下0star的作者

写来玩的～star不重要，主要是当时自己开心

**Comment by windshadow233** [comment]
> ![图片](https://user-images.githubusercontent.com/87431097/264465254-c2289ee7-3fb0-4483-b04a-5ac29dd85881.png)
> 这是什么情况

哈哈哈，我当时写的时候对里面出现的文件路径写的不严谨。可能需要把src作为工作目录。
